### ISSUE TITLE
What is the best way to render a compiled Ember template to a string?

### ISSUE THREAD

**Issue by OrKoN** [embersherpa/ama#16]
I used to do the following:

``` JavaScript
  var controller = Ember.Controller.create({
    name: 'templateToString'
  });

  var view = Ember.View.create({
    template: template,
    controller: controller
  });

  view.createElement();
  return view.element.innerHTML;
```

But I am not sure if this method is still reliable.

**Comment by taras** [comment]
What version of Ember are you running?

**Comment by OrKoN** [comment]
I am on Ember 1.13.6 but looking for a future-proof solution.

**Comment by taras** [comment]
I'm assuming that by future proof solution, you're also referring to doing this with a Component not Controllers + Views. Is this correct?

**Comment by OrKoN** [comment]
Or a better solution. Because creating a component just to render a template does not feel correct. This solution with views does not work reliably for me. So I guess with components it's going to be about the same. Also it seems that an instance of an Ember `container` needs to be provided to a dynamically created component which I would like to avoid: without a container instance it does not find app helpers  and other components. So I am really looking for a best practice here.

**Comment by taras** [comment]
This isn't a common use case, so I would say that there is no best practices. There might however be a good solution; we can try to look for that.

**Comment by taras** [comment]
Can you describe your use case and give an example of a template that you're trying to render?

**Comment by OrKoN** [comment]
The template is user-provided so theoretically it can be anything. Currently, it's a simple call of `t` helper to localize a message. It's compiled by the server on-the-fly using the corresponding compiler for the client's Ember version so it comes to the client as a string:

```
(function() {
  return {
    meta: {
      "revision": "Ember@1.13.6",
      "loc": {
        "source": null,
        "start": {
          "line": 1,
          "column": 0
        },
        "end": {
          "line": 2,
          "column": 0
        }
      }
    },
    arity: 0,
    cachedFragment: null,
    hasRendered: false,
    buildFragment: function buildFragment(dom) {
      var el0 = dom.createDocumentFragment();
      var el1 = dom.createComment("");
      dom.appendChild(el0, el1);
      var el1 = dom.createTextNode("\n");
      dom.appendChild(el0, el1);
      return el0;
    },
    buildRenderNodes: function buildRenderNodes(dom, fragment, contextualElement) {
      var morphs = new Array(1);
      morphs[0] = dom.createMorphAt(fragment,0,0,contextualElement);
      dom.insertBoundary(fragment, 0);
      return morphs;
    },
    statements: [
      ["inline","t",["checkout.terms"],[],["loc",[null,[1,0],[1,22]]]]
    ],
    locals: [],
    templates: []
  };
}())
```

This string is then `eval`ed and passed to Ember.HTMLBars.template and the result of the `template` method is used to render the template to a variable. This variable is later rendered in a static template.
The problem is that sometimes I get a properly rendered string (i.e. the result of `t` helper) but sometimes I get the source code of the template in the variable:

```
 (function() { return { meta: { "revision": "Ember@1.13.6", "loc": { "source": null, "start": { "line": 1, "column": 0 }, "end": { "line": 2, "column": 0 } } }, arity: 0, cachedFragment: null, hasRendered: false, buildFragment: function buildFragment(dom) { var el0 = dom.createDocumentFragment(); var el1 = dom.createComment(""); dom.appendChild(el0, el1); var el1 = dom.createTextNode("\n"); dom.appendChild(el0, el1); return el0; }, buildRenderNodes: function buildRenderNodes(dom, fragment, contextualElement) { var morphs = new Array(1); morphs[0] = dom.createMorphAt(fragment,0,0,contextualElement); dom.insertBoundary(fragment, 0); return morphs; }, statements: [ ["inline","t",["checkout.terms"],[],["loc",[null,[1,0],[1,22]]]] ], locals: [], templates: [] }; }())
```

**Comment by taras** [comment]
The difference between Handlebars and HTMLBars is that HTMLBars is designed for dynamic parts that update as state changes. It sounds like what you need is just a Handlebars template which is much easier to work with.

``` js
var context = {
  title: "My New Post", 
  body: "This is my first post!"
};
var result = template(context);
```

Would that work?

**Comment by OrKoN** [comment]
Yes, it worked (migrating away from it). But too problems with this solution: 1) it will not use existing HtmlBars helpers 2) it will add some more KB of Javascript on the client

**Comment by taras** [comment]
I have reservations about this entire thread because I'm answering downstream questions to a very uncommon problem. My instinct is telling me that there might be a better solution to an upstream problem  where this becomes unnecessary or less complicated.

**Comment by OrKoN** [comment]
I have found a solution/a workaround that works for me in Ember 2.0 https://60devs.com/hacky-way-to-render-ember-template-to-string-in-ember-2-0.html 

Thanks for your input, Taras! Please share your thoughts on the solution I have found.
