### ISSUE TITLE
What does your current Ember CRUD look like?

### ISSUE THREAD

**Issue by jerel** [embersherpa/ama#17]
Ember is opinionated but there's certainly room for personal coding styles. Especially now that we're nearing 2.x there's quite a bit of flexibility (mutation, actions up/data down, string actions vs passing functions, components with no controllers, etc). Just curious what it would look like if you were to implement a create/edit form on `canary` today.

**Comment by taras** [comment]
I'm working on that this week. I'll share something soon. Stay tuned :)

**Comment by taras** [comment]
In case you missed it, I'll be giving a workshop on Ember CRUD http://www.meetup.com/Ember-Global-Meetup/events/224541190/
