### ISSUE TITLE
What is the best way to handle remote events?

### ISSUE THREAD

**Issue by renefs** [embersherpa/ama#20]
I am working on an application that receives a lot of different events from a remote server, but I am not completely sure of what is the best way to handle them (for example I have a list of things that is updated when the application receives an event from a remote server and I would like to update the number of items). Should I use different components to keep the related events handlers separated, should I use several helpers, several controllers?

Thank you.

**Comment by taras** [comment]
It sounds like you probably want to create a service that will connect to the remote server and receive events. In your application, you can then inject this service into whatever components need to listen for these events.

Let me know if you'd like me to create a demo of how this might look.

**Comment by renefs** [comment]
Hi taras,

I would be very thankful if you create an example of this. Would it be possible to trigger a route transition from an injected service in it? (Something like the service receiving a "connection successful" event and triggers the transition to the user dashboard route).

Thank you very much.

**Comment by taras** [comment]
@renefs87 sorry for the delay getting back to you about this. 

A general pattern for working with remote events is to create a _service_ that connects  to the remote server, listens to remote events and provides an interface for other components of the application to respond to these events. 

Let's look at these individual parts one at a time.

## 1. Connecting to remote server

There are 2 common ways of initiating a connection to a remote server.

### a. Via `init`

``` javascript
import Ember from 'ember';

const {
  Service,
  on
} = Ember;

export default Service.extend({
  status: null,
  openConnection: on('init', function(){
    // open connection here
    // typically, you'll have to pass a callback that will be triggered asynchronously 
    // Ember.run.bind returns a function that's bound to given context and wraps the provided callback in Ember.run
    someService.connect(Ember.run.bind(this, this.connect));
  }),
  connect() {
    this.set('status', 'connected');
  }
})
```

### b. Via Application Route model or beforeModel hook

In some scenarios, you need to ensure that the service connected before the user can access other parts of the application. In this case, you should connect in the application's `beforeModel` or `model` hooks.
- Use `beforeModel` if you need to use result of the connection in the `model` hook. 
- Use `model` hook if the result of the connection has to be set as model value on `applications/controller`.

In `routes/application.js`

``` javascript
import Ember from 'ember';

export default Ember.Route.extend({
  remote: Ember.inject.service(),
  beforeModel() {
    return this.get('remote').connect();
  }
});
```

In `services/route.js`

``` javascript
import Ember from 'ember';

export default Ember.Service.extend({
  connect() {
    // you must return a Promise to tell Ember's Router to wait for the Promise to resolve before continuing
    return new Ember.RSVP.Promise(function(resolve, reject){
      someservice.connect(function(err, data) {
        if (err) {
          reject(error);
        }
        resolve(data);
      });
    });
  }
});
```

## 2. Listen to remote events

You will likely want to listen for additional events triggered by the remote service. To do this, you'll need to bind events on your remote service to methods on your application's service.

``` javascript
import Ember from 'ember';

const { on } = Ember;

export default Ember.Service.extend({
  bindEvents: on('init', function() {
    const appService = this;
    // how this is done depends on your's service's API, but here is how it might look
    var client = new SomeService({
      disconnect: function() {
        appService.disconnect();
      }
    });
    // it might also look like this
    // someservice.onDisconnect = Ember.run.bind(this, this.disconnect);
    // or like this
    // someservice.on('disconnect', Ember.run.bind(this, this.disconnect);
  });
  disconnect() {
    this.set('status', 'disconnected');
  }
});
```

## 3. Provides an API

Every system has 💩that we would prefer to not deal with. Services allow us to provide clean APIs to 💩. You can use `Ember.Evented` mixin to allow your services to trigger events for other components of your application to consume.

In `services/remote.js`

``` javascript
import Ember from 'ember';

const { 
  Evented
} = Ember;

export default Ember.Service.extend(Evented, {
  disconnect() {
    // 
    this.trigger('connection-lost');
  }
});
```

In `routes/application.js`

``` javascript
import Ember from 'ember';

const { on } = Ember;

export default Ember.Route.extend({
  remote: Ember.inject.service(),
  bindRemote: on('init', function() {
    const remote = this.get('remote');
    remote.on('connection-lost',()=>{
      this.transitionTo('index');
    });
  })
});
```

---

I created an [Ember Twiddle that shows your specific use case](http://ember-twiddle.com/6d4c105dda2f88c3f7cf) and [here is the gist for it](https://gist.github.com/taras/6d4c105dda2f88c3f7cf).

**Comment by molefrog** [comment]
@taras I often have a situation when I need some background service to reinitialize itself when user logs in/out. For example, I have different per-user websocket endpoints and `RealTimeService` (lets call it like this) has to resubscribe when the session is changed.

So I came up with the following solution: I have `SessionService` that holds `currentUser` property and provides login/logout features for components. And then `RealTimeService` simply observes that property and does all the things. 

Is that a good practice? I've heard somewhere that we should avoid observers as much as possible, since Ember adopts this new React-like one-way data binding behaviour. Theoretically it's possible for the `currentUser` prop to reassigned to the same value, so the observer will be fired when then current session hasn't been in fact changed.

**Comment by taras** [comment]
@molefrog IMO, using observers in the scenario is acceptable, but I would recommend that you use `Evented` as API rather than observer as API. Do you need further clarification on what I'm suggesting?

**Comment by molefrog** [comment]
@taras Well, it's pretty clear now, I guess subscribing on `init` would work. Thanks!

**Comment by renefs** [comment]
Thank you very much for your help. I forgot to answer and I am closing this now.
