### ISSUE TITLE
What feature would you like to see in Ember 3.0?

### ISSUE THREAD

**Issue by BFalkner** [embersherpa/ama#21]

**Comment by alexlafroscia** [comment]
I'm looking forward to tree shaking (meaning that only the parts of Ember that you're actually using are included in the build) but that might land before Ember 3.0.  I know there's a lot of work going on right now to make that happen.

**Comment by taras** [comment]
Ember 3.0 is so far away, but I'd like to see:
1. not having to use this.get & this.set
2. being able to break the app into multiple apps with Engines
3. a backend API that builds itself from your Ember Data models

That's all I got for now.

**Comment by alexlafroscia** [comment]
> not having to use this.get & this.set

I think this is on the roadmap, right? I heard that once they ditch IE 8 support (which 2.0 does) it would be possible

**Comment by taras** [comment]
> I think this is on the roadmap, right?

Yeah, I think so.

**Comment by BFalkner** [comment]
Tree shaking, CP accessors and Engines are all kinda planned for the 2 line.
I'm sure a backend running from ED models will come about but would this really be considered part of Ember itself?

I think I was hoping for something more future looking, that's still just a thought. But good enough. :)

**Comment by taras** [comment]
> I'm sure a backend running from ED models will come about but would this really be considered part of Ember itself?

No, but I see Ember as Ember ecosystem, not just the core.

> I think I was hoping for something more future looking, that's still just a thought. But good enough. :)

When Ember 1.0 came out, I'm pretty sure no-one could imagine that React would cause such a stir, but here we are. I wish I had something more exciting to share :)

**Comment by greyhwndz** [comment]
Hope Fastboot would be production ready :)
