### ISSUE TITLE
How can I test an initializer that needs Ember Data models?

### ISSUE THREAD

**Issue by billpull** [embersherpa/ama#4]
Currently have this SO question open about testing initializers
http://stackoverflow.com/questions/31437916/ember-test-intializer-that-requires-model

I have an initializer that registers some modules with the application from a JSON object on the page in a script tag. Works fine in the application but the test fails because it cannot find the models that are expected.

initialzers/bootstrap-payload.js

``` js
export function initialize(container, application) {
  var store = container.lookup('service:store'),
    payloadKeys = Object.keys(BOOTSTRAP_DATA);

  payloadKeys.forEach((key) => {
    var registryKey = `bootstrap-payload:${key}`,
        model;

    model = store.createRecord(key, BOOTSTRAP_DATA[key]);
    application.register(registryKey, model, {instantiate:false});
  });
}

export default {
  name: 'bootstrap-payload',
  after: 'ember-data',
  initialize: initialize
};
```

tests/initializers/bootstrap-payload-test.js

``` js
import Ember from 'ember';
import { initialize } from '../../../initializers/bootstrap-payload';
import { module, test } from 'qunit';

var registry, application;

module('Unit | Initializer | bootstrap payload', {
  needs: ['model:channel'],

  beforeEach: function() {
    Ember.run(function() {
      application = Ember.Application.create();
      registry = application.registry;
      application.deferReadiness();
    });
  }
});

// Replace this with your real tests.
test('it works', function(assert) {
  initialize(registry, application);

  // you would normally confirm the results of the initializer here
  assert.ok(true);
});
```

tests/index.html includes an example `BOOTSTRAP_DATA` variable in it that contains a model that is always expected to be there called `channel`. When running ember test I get the following error.

`at http://localhost:7357/assets/test-support.js:5604: No model was found for 'channel'`
How can I inject this dependency the needs field doesn't seem to work in this case. Or is there anyway to make the initializer more testable.

**Comment by taras** [comment]
Good question. I created a [demo app with your code](https://github.com/embersherpa/test-models-in-initializer)

Please add an example of the `BOOTSTRAP_DATA` and I'll see what we can do to make it work.

**Comment by taras** [comment]
The initializer test doesn't use priority that you specify when setting up the initializer. If you look at how the test is written, it's actually only working with the initialize function. You can see this at the top of the test `import { initialize } from '../../../initializers/bootstrap-payload';` So, Ember Data isn't initialized and therefore Models are not registered with the resolver.

I made you test work by [explicitly registered the model with the registry in the test](https://github.com/embersherpa/test-models-in-initializer/blob/c620c81c98563671a38f77c0313266d72ab1f943/tests/unit/initializers/bootstrap-payload-test.js#L21) and started the run loop in [your initializer](https://github.com/embersherpa/test-models-in-initializer/blob/c620c81c98563671a38f77c0313266d72ab1f943/app/initializers/bootstrap-payload.js#L11).

It's not clear what the proper solution for this is.

**Comment by taras** [comment]
A better way to test this might be with an [acceptance test that doesn't visit any route](https://github.com/embersherpa/test-models-in-initializer/blob/master/tests/acceptance/index-test.js).

But I think the best way to do this will be with some kind of integration test. There was an issue to allow [moduleFor\* integration: true](https://github.com/rwjblue/ember-qunit/issues/108) but it seems to be closed.

**Comment by billpull** [comment]
@taras thanks! I think I will go with the acceptance test for now looks like it asserts all I need to know about that initializer.
