### ISSUE TITLE
Ember simple-auth with Node Passport

### ISSUE THREAD

**Issue by calouette** [embersherpa/ama#7]
I am setting up a new Ember app with a Node.js backend. I want to get Authentication/Authorization down first and I have successfully setup authentication through facebook using simple-auth and torii so far in the frontend.

My next step is for Node.js Passport to take over and deal with further authentication and authorization in the backend. Is this a logical step or would you use different technologies?

**Comment by taras** [comment]
I don't know specifically about simple-auth with Node Passport but you might want to checkout [Sane Stack](http://sanestack.com) which is Ember + Sails.js. There is an authentication library for Sails.js called Watercock and you can see an example of authorization done with [Ember + Sails.js + Waterlock](https://github.com/Globegitter/sails-ember-waterlock-auth). There is a [video about Sane Stack on Ember London meetup page](https://vimeo.com/132203795).

I'm not sure if it's a better solution than going with Passport.js but at least the path is paved a little.

@bttf I believe you have some experience with doing Authentication between Ember & Node. What do you think?

**Comment by taras** [comment]
I found a blogpost by @givanse on [doing Authentication with Sane Stack](http://givan.se/sane-auth-example/)

**Comment by givanse** [comment]
Probably you don't need Passport, just something that can handle OAuth/JWT tokens. see: [ember-and-sails-authentication-options/#tl-dr](http://givan.se/ember-and-sails-authentication-options/#tl-dr)

**Comment by taras** [comment]
Thank you @givanse

**Comment by calouette** [comment]
Thanks guys! I'm going to look into Sane Stack
